name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
        
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Compile project
      run: |
        make platform=ps2 clean all

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: freeintv_libretro_ps2-${{ steps.slug.outputs.sha8 }}
        path: freeintv_libretro_ps2.a
